### ISSUE TITLE
[react-native-tab-view] Navigating to end of tab list breaks lazy logic

### ISSUE THREAD

**Issue by jbinda** [callstack/react-native-open-source-board#133]
[https://github.com/react-native-community/react-native-tab-view/issues/87](https://github.com/react-native-community/react-native-tab-view/issues/87)

**Comment by Bardiamist** [comment]
Also Satya removed `animationEnabled` https://github.com/react-native-community/react-native-tab-view/issues/707#issuecomment-472003989 Also very bad situation with TypeScript types. Now is not good time of react navigation.
