### ISSUE TITLE
[react-native-maps] Feature Request: Provide onUserLocationChange for use with MapKit (iOS)

### ISSUE THREAD

**Issue by michalchudziak** [callstack/react-native-open-source-board#30]
[https://github.com/react-native-community/react-native-maps/issues/2055](https://github.com/react-native-community/react-native-maps/issues/2055)

**Comment by Taym95** [comment]
I would like to take this issue!

**Comment by ptrocki** [comment]
Resolved https://github.com/react-native-community/react-native-maps/pull/2889
