### ISSUE TITLE
[react-native-tab-view] RTL is not supported!

### ISSUE THREAD

**Issue by michalchudziak** [callstack/react-native-open-source-board#33]
https://github.com/react-native-community/react-native-tab-view/issues/184

**Comment by Abdo-zayed** [comment]
any solution ?

**Comment by Abdo-zayed** [comment]
in TabBar.js
modify this function
_this.resetScroll = function (value) {
const tabLength=this.props.navigationState.routes.length-1;

        const target=I18nManager.isRTL?tabLength-value:value;
        console.log(tabLength+' '+target)
        if (_this.props.scrollEnabled) {
            _this.scrollView && _this.scrollView.scrollTo({
                x: _this.getScrollAmount(_this.props, _this.state,target),
                animated: true
            });
        }
    };
