### ISSUE TITLE
[react-native-webview] onShouldStartLoadWithRequest don't work on Android

### ISSUE THREAD

**Issue by michalchudziak** [callstack/react-native-open-source-board#38]
https://github.com/react-native-community/react-native-webview/issues/185

**Comment by ptrocki** [comment]
Resolved in https://github.com/react-native-community/react-native-webview/pull/619

**Comment by ptrocki** [comment]
This discussion is a little bit complicated https://github.com/react-native-community/react-native-webview/issues/229 and someone propose PR for this feature https://github.com/react-native-community/react-native-webview/pull/397/files
